### ISSUE TITLE
In MS Edge options, you can't read the dropdown text until hover

### ISSUE THREAD

**Issue by Keith94** [FaisalBinAhmed/tabius#6]
![image](https://github.com/FaisalBinAhmed/tabius/assets/5490615/8537ffc5-2654-41fc-bc6b-60f5f8b9cc63)

**Comment by FaisalBinAhmed** [comment]
Hi @Keith94<
is it on Windows and from Microsoft Edge store?

**Comment by Keith94** [comment]
Hi yes I believe so

**Comment by FaisalBinAhmed** [comment]
I think this is fixed on the Chrome version. I was being lazy and didn't publish the latest version on Edge store. I will do it for the next version.

For now, you can download it from Chrome store: https://chromewebstore.google.com/detail/tabius-automatic-tab-grou/enceimdjnaccoeikjobaeicfodlfnijp 

let me know if that solves it, otherwise, I will issue an update :)

**Comment by Keith94** [comment]
I installed the chrome version and the issue still happens

Tabius 2.0.1
Edge 121.0.2277.106

**Comment by FaisalBinAhmed** [comment]
I will issue a fix soon. :)
